project:
  type: website
  output-dir: docs
  resources:
    - "files/**"

# Meta
description-meta: "Liam Kirkpatrick's Personal Website"
author-meta: "Liam Kirkpatrick"

website:
  title: "Liam Kirkpatrick"
  image: "https://quarto.org/quarto.png"
  description: "Liam Kirkpatrick's Personal Website"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: Contact
            href: contact.qmd             
      - text: Research 
        menu:
          - text: Fieldwork
            href: posts.qmd#category=fieldwork   
      - text: Outreach
        menu:        
        - text: Presentations
          href: posts.qmd#category=presentation                   

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/liamkirkpatrick
        target: _blank    

  
  page-navigation: true
  
  page-footer: 
    left: "[Liam Kirkpatrick](https://github.com/liamkirkpatrick/liamkirkpatrick.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    right:  
      - icon: github
        href: https://github.com/liamkirkpatrick
        target: _blank

  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/liamkirkpatrick/liamkirkpatrick.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://liamkirkpatrick.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

